#!/bin/bash
export TMPDIR=/home/iamasq/apps/gd2-a1/tmp
mkdir -p /home/iamasq/apps/gd2-a1/tmp
PIDFILE="/home/iamasq/apps/gd2-a1/tmp/node.pid"
NODE=/bin/node

if [ -e "$PIDFILE" ] && (pgrep -u iamasq | grep -x -f $PIDFILE &> /dev/null); then
  echo "Node.js for gd2-a1 already running."
  exit 99
fi

cd /home/iamasq/apps/gd2-a1
/usr/sbin/daemonize -c /home/iamasq/apps/gd2-a1 -e ~/logs/apps/gd2-a1/node_error.log -o ~/logs/apps/gd2-a1/node_output.log -p $PIDFILE $NODE app.js

echo "Started Node.js for gd2-a1."
